version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
