name: Comprehensive Test Suite

on:
  push:
  pull_request:

jobs:
  component-tests:
    name: Component Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run component tests
        run: npx jest --testPathPattern=__tests__/components/ --no-coverage
        env:
          NODE_ENV: test

      - name: Upload component test coverage
        uses: actions/upload-artifact@v4
        with:
          name: component-coverage
          path: coverage/
          if-no-files-found: warn

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run API tests
        run: npx jest --config=jest.config.cjs --testPathPattern=__tests__/api/ --no-coverage
        env:
          NODE_ENV: test
          # Default to empty JSON object for credentials - Firebase client code will handle missing credentials
          GOOGLE_APPLICATION_CREDENTIALS: '{}'
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: Upload API test coverage
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: coverage/
          if-no-files-found: warn

  utility-tests:
    name: Utility Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run utility and other tests
        run: npx jest --config=jest.config.cjs --testPathPattern='^(?!__tests__/(components|api)/)'
        env:
          NODE_ENV: test
          # Default to empty JSON object for credentials - Firebase client code will handle missing credentials
          GOOGLE_APPLICATION_CREDENTIALS: '{}'
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: Upload utility test coverage
        uses: actions/upload-artifact@v4
        with:
          name: utility-coverage
          path: coverage/
          if-no-files-found: warn

  # This job just collects artifacts and doesn't re-run tests
  combine-coverage:
    name: Combine Coverage Reports
    runs-on: ubuntu-latest
    needs: [component-tests, api-tests, utility-tests]
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: '*-coverage'
          path: coverage-reports

      - name: List coverage reports
        run: find coverage-reports -type f | sort

      - name: Upload combined coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: all-coverage-reports
          path: coverage-reports/
          if-no-files-found: warn
