name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload wordpress/plugins to server via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ANANDA_ORG_PROD_SFTP_SERVER }}
          username: ${{ secrets.ANANDA_ORG_PROD_SFTP_USER }}
          password: ${{ secrets.ANANDA_ORG_PROD_SFTP_PASSWORD }}
          port: 22
          source: "wordpress/plugins/*"
          target: "/public_html/wp-content/plugins/"
