name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload wordpress/plugins to server via SFTP
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PASSWORD: ${{ secrets.ANANDA_ORG_PROD_SFTP_PASSWORD }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "wordpress/plugins/"
          REMOTE_HOST: ${{ secrets.ANANDA_ORG_PROD_SFTP_SERVER }}
          REMOTE_USER: ${{ secrets.ANANDA_ORG_PROD_SFTP_USER }}
          TARGET: "/home/master/applications/ananda/public_html/wp-content/plugins/"
          EXCLUDE: "/node_modules/"
