name: Deploy Public Chatbot Plugin to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy wordpress/plugins folder via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLOUDWAYS_SSH_KEY }}" > ~/.ssh/id_chatbotdepl
          chmod 600 ~/.ssh/id_chatbotdepl
          ssh-keyscan -H 45.63.93.73 >> ~/.ssh/known_hosts

      - name: Deploy plugin folder via rsync
        run: |
          rsync -avz --delete ./wordpress/plugins/ananda-ai-chatbot/ \
            github-ananda-org@45.63.93.73:/home/master/applications/aghzsnrmqf/public_html/wp-content/plugins/ananda-ai-chatbot/
