name: Run All Tests

on:
  push:
    branches: [main, develop, unit-tests]
  pull_request:
    branches: [main, develop, unit-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run all tests
        run: npm test
        env:
          NODE_ENV: test
          # Add placeholder for Firebase credentials - these should be set as GitHub secrets
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          # Add other environment variables as needed
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          if-no-files-found: warn
